### ISSUE TITLE
Use native YAML lists instead of comma-delimited strings.

### ISSUE THREAD

**Issue by tima** [stephenpc/ansible-satellite#3]
Re:

```
     repo_ids: "2,3,4,6,7,8,9"
```

This is a small thing, but I recommend you represent a list of values as a native YAML list instead of string as you do. I realize the hammer tool this is for needs a comma delimited list as a param. You can assemble that string using a filter like so...

```
{{ repo_ids | join(',') }}
```

...and have the option of applying any other list operations or functions you might need like getting a count of the elements or sorting the list.

**Comment by stephenpc** [comment]
Implemented. Thank you.
